### ISSUE TITLE
What about the game name?

### ISSUE THREAD

**Issue by agudulin** [lunatik-210/QoHG--game-engine#12]
2D-Experiments are no more just experiments. We have the competitor, potential {audience, a lot of money and girls}. So a cool name for the game is something important we need!

**Comment by lunatik-210** [comment]
Yes, i agree ;) So lets think about it!!
Lets determine the idea first! 

So its 2D RTS with RPG elements, you may craft buildings and some stuff.
The world is too large, but not infinite!
There can be some goals, for example you should find some artifacts and hold it in your capital.

Well, may be "Kingdoms" or "Lost Kingdoms" - потерянны королевства, sounds nice but have no much sense =)

**Comment by agudulin** [comment]
Well, the question is open :)

**Comment by lunatik-210** [comment]
I've an Idea, what about "В поисках Святого Грааля", I've described it in Goodle Doc -> 2D Strategy. Please, have a look, what do you think about?

**Comment by lunatik-210** [comment]
Well, it's kind of we have decided one for the time, will continue discussion later on a new stage of development!
