### ISSUE TITLE
Develop smart texture loader!

### ISSUE THREAD

**Issue by lunatik-210** [lunatik-210/QoHG--game-engine#14]
subj

**Comment by agudulin** [comment]
There is effort to start develop texture map class.

What texture loader is?
Well, we have archive of two files: objects_textures.png and monsters_textures.png. Also we set the rule: for example, no more than 8 images per raw in texture file.
So TextureLoader should unzip the archive and convert textures files into Map Class object. Thats it? What else?

**Comment by lunatik-210** [comment]
I think that for now thats it! But look at this example http://inventwithpython.com/pyganim/  It's great way to make animation for characters! I think we will use it! So, for every object there will be 10-20 textures = Sprite, and then it would be better to make Texture file for every object, and after loading hold image name in hash.
So there will be:
1) Blocks: grass, water so on...
2) Monsters as a Sprite with ~10 textures in one!
3) Smth else?

**Comment by lunatik-210** [comment]
I've just found that there is a bug with new version of loader, here there is some black blocks http://i47.tinypic.com/288no5l.png, may you deep into that, please?)

**Comment by lunatik-210** [comment]
Well, I think the task is Done, so I close issue, If smth will nedded we should open new one!
