### ISSUE TITLE
config.py have to be refactored

### ISSUE THREAD

**Issue by lunatik-210** [lunatik-210/QoHG--game-engine#9]

**Comment by agudulin** [comment]
It's just XML files parsing, what are you waiting from that code?

**Comment by lunatik-210** [comment]
I don't no, but I written so ugly code =)

**Comment by lunatik-210** [comment]
Do you think we should throw it out, and close the tickets? probably it okay, may be we are really don't need refactor it!

**Comment by agudulin** [comment]
Yep, closed as partially invalid.
